### ISSUE TITLE
Cannot load .mat annotation file using python.

### ISSUE THREAD

**Issue by LuckyDC** [cvgroup-njust/CityPersons#5]
I attempt to load the annotation file using scipy
```
import scipy.io as sio
sio.loadmat('anno_train.mat')
```
However, the code raises error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chuanchen_luo/anaconda3/envs/ps/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 225
, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/chuanchen_luo/anaconda3/envs/ps/lib/python3.7/site-packages/scipy/io/matlab/mio.py", line 74,
 in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home/chuanchen_luo/anaconda3/envs/ps/lib/python3.7/site-packages/scipy/io/matlab/miobase.py", line
 231, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 109, 101
```
I tried a lot to address it but failed. Would you like to give a solution?

**Comment by LuckyDC** [comment]
Sorry. I found that the file is corrupted while downloading. It's my mistake. So, close the issue
